CREATE TABLE `workout_stats` (
	`workout_id` text(21) PRIMARY KEY NOT NULL,
	`user_id` text(21) NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`attempts` integer DEFAULT 0 NOT NULL,
	`next_run_at` integer DEFAULT (strftime('%s','now') * 1000) NOT NULL,
	`last_error` text,
	`locked_at` integer,
	`avg_heart_rate` integer,
	`min_heart_rate` integer,
	`max_heart_rate` integer,
	`mhr_used` integer,
	`avg_intensity` integer,
	`min_intensity` integer,
	`max_intensity` integer,
	`active_calories` real,
	`total_calories` real,
	`heart_rate_recovery` integer,
	`heart_rate_recovery_two_minutes` integer,
	`active_score` integer,
	`avg_mets` real,
	`distance_meters` real,
	`pace_seconds_per_km` real,
	`cadence` integer,
	`zone_1_seconds` integer,
	`zone_2_seconds` integer,
	`zone_3_seconds` integer,
	`zone_4_seconds` integer,
	`zone_5_seconds` integer,
	`zone_1_minutes` real,
	`zone_2_minutes` real,
	`zone_3_minutes` real,
	`zone_4_minutes` real,
	`zone_5_minutes` real,
	`hr_time_series` text,
	`hr_recovery_series` text,
	`created_at` integer DEFAULT (strftime('%s','now') * 1000) NOT NULL,
	`updated_at` integer DEFAULT (strftime('%s','now') * 1000) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `workout_stats_queue_idx` ON `workout_stats` (`status`,`next_run_at`);--> statement-breakpoint
CREATE INDEX `workout_stats_user_idx` ON `workout_stats` (`user_id`,`updated_at`);